// <auto-generated />
using System;
using AzureDevopsWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AzureDevopsWebAPI.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20230220233108_addingEmailToIndividiualModel")]
    partial class addingEmailToIndividiualModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AzureDevopsWebAPI.Models.AccessLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AccessLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Project Manager"
                        },
                        new
                        {
                            Id = 2,
                            Value = "Lead Developers"
                        },
                        new
                        {
                            Id = 3,
                            Value = "Senior Developers"
                        },
                        new
                        {
                            Id = 4,
                            Value = "Mid-Level Developers"
                        },
                        new
                        {
                            Id = 5,
                            Value = "Junior Developers"
                        },
                        new
                        {
                            Id = 6,
                            Value = "Trainee Developers"
                        },
                        new
                        {
                            Id = 7,
                            Value = "Everyone"
                        });
                });

            modelBuilder.Entity("AzureDevopsWebAPI.Models.ChangeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("IndividualId")
                        .HasColumnType("int");

                    b.Property<int?>("ItemTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemTypeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ChangeLogs");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            EndDateTime = new DateTime(2023, 2, 18, 2, 40, 0, 0, DateTimeKind.Unspecified),
                            IndividualId = 220130051,
                            ProjectId = 3,
                            StartDateTime = new DateTime(2023, 2, 17, 13, 47, 40, 0, DateTimeKind.Unspecified),
                            Summary = "Auditing Financial Statements"
                        });
                });

            modelBuilder.Entity("AzureDevopsWebAPI.Models.Individual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccessLevelId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccessLevelId");

                    b.ToTable("Individuals");

                    b.HasData(
                        new
                        {
                            Id = 221028080,
                            AccessLevelId = 1,
                            Email = "221028080@students.nust.na",
                            FirstName = "King",
                            LastName = "Hiholike"
                        },
                        new
                        {
                            Id = 217030203,
                            AccessLevelId = 2,
                            Email = "217030203@students.nust.na",
                            FirstName = "Aron",
                            LastName = "Indongo"
                        },
                        new
                        {
                            Id = 221128220,
                            AccessLevelId = 6,
                            Email = "221128220@students.nust.na",
                            FirstName = "Max",
                            LastName = "Haikali"
                        },
                        new
                        {
                            Id = 220130051,
                            AccessLevelId = 3,
                            Email = "220130051@students.nust.na",
                            FirstName = "Takudzwa",
                            LastName = "Kucherera"
                        });
                });

            modelBuilder.Entity("AzureDevopsWebAPI.Models.ItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ItemTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Planning & Analysis"
                        },
                        new
                        {
                            Id = 2,
                            Value = "System Design"
                        },
                        new
                        {
                            Id = 3,
                            Value = "Development"
                        },
                        new
                        {
                            Id = 4,
                            Value = "Verification & Testing"
                        },
                        new
                        {
                            Id = 5,
                            Value = "Documentation"
                        },
                        new
                        {
                            Id = 6,
                            Value = "System Audit"
                        });
                });

            modelBuilder.Entity("AzureDevopsWebAPI.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessLevelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccessLevelId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessLevelId = 1,
                            Name = "Fin-Statements Software Review"
                        },
                        new
                        {
                            Id = 2,
                            AccessLevelId = 2,
                            Name = "Financials Database Design"
                        },
                        new
                        {
                            Id = 3,
                            AccessLevelId = 7,
                            Name = "Asset-Management System Audit"
                        },
                        new
                        {
                            Id = 4,
                            AccessLevelId = 5,
                            Name = "Payroll Software UI Developmet"
                        },
                        new
                        {
                            Id = 5,
                            AccessLevelId = 5,
                            Name = "Customer Balance API Review"
                        });
                });

            modelBuilder.Entity("AzureDevopsWebAPI.Models.ChangeLog", b =>
                {
                    b.HasOne("AzureDevopsWebAPI.Models.ItemType", "ItemType")
                        .WithMany()
                        .HasForeignKey("ItemTypeId");

                    b.HasOne("AzureDevopsWebAPI.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemType");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AzureDevopsWebAPI.Models.Individual", b =>
                {
                    b.HasOne("AzureDevopsWebAPI.Models.AccessLevel", "AccessLevel")
                        .WithMany()
                        .HasForeignKey("AccessLevelId");

                    b.Navigation("AccessLevel");
                });

            modelBuilder.Entity("AzureDevopsWebAPI.Models.Project", b =>
                {
                    b.HasOne("AzureDevopsWebAPI.Models.AccessLevel", "AccessLevel")
                        .WithMany()
                        .HasForeignKey("AccessLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessLevel");
                });
#pragma warning restore 612, 618
        }
    }
}
