// <auto-generated />
using System;
using AzureDevopsWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AzureDevopsWebAPI.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20230216144016_addingIndividualDBSET")]
    partial class addingIndividualDBSET
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AzureDevopsWebAPI.Models.AccessLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AccessLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Project Manager"
                        },
                        new
                        {
                            Id = 2,
                            Value = "Lead Developers"
                        },
                        new
                        {
                            Id = 3,
                            Value = "Senior Developers"
                        },
                        new
                        {
                            Id = 4,
                            Value = "Mid-Level Developers"
                        },
                        new
                        {
                            Id = 5,
                            Value = "Junior Developers"
                        },
                        new
                        {
                            Id = 6,
                            Value = "Trainee Developers"
                        },
                        new
                        {
                            Id = 7,
                            Value = "Everyone"
                        });
                });

            modelBuilder.Entity("AzureDevopsWebAPI.Models.ChangeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("IndividualId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ChangeLogs");
                });

            modelBuilder.Entity("AzureDevopsWebAPI.Models.Individual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessLevelId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccessLevelId");

                    b.ToTable("Individuals");
                });

            modelBuilder.Entity("AzureDevopsWebAPI.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessLevelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccessLevelId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessLevelId = 1,
                            Name = "Asset Management Software"
                        },
                        new
                        {
                            Id = 2,
                            AccessLevelId = 2,
                            Name = "Payroll Database"
                        },
                        new
                        {
                            Id = 3,
                            AccessLevelId = 7,
                            Name = "Email Streaming Platform"
                        },
                        new
                        {
                            Id = 4,
                            AccessLevelId = 5,
                            Name = "Financial Statements Automation"
                        });
                });

            modelBuilder.Entity("AzureDevopsWebAPI.Models.ChangeLog", b =>
                {
                    b.HasOne("AzureDevopsWebAPI.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AzureDevopsWebAPI.Models.Individual", b =>
                {
                    b.HasOne("AzureDevopsWebAPI.Models.AccessLevel", "AccessLevel")
                        .WithMany()
                        .HasForeignKey("AccessLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessLevel");
                });

            modelBuilder.Entity("AzureDevopsWebAPI.Models.Project", b =>
                {
                    b.HasOne("AzureDevopsWebAPI.Models.AccessLevel", "AccessLevel")
                        .WithMany()
                        .HasForeignKey("AccessLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessLevel");
                });
#pragma warning restore 612, 618
        }
    }
}
